export const events = [
'Prepare 2016 Financial', 
'Prepare 2016 Marketing Plan', 
'Update Personnel Files', 
'Review Health Insurance Options Under the Affordable Care Act', 
'New Brochures', 
'2016 Brochure Designs', 
'Brochure Design Review', 
'Website Re-Design Plan', 
'Rollout of New Website and Marketing Brochures',
 'Update Sales Strategy Documents', 
'Create 2012 Sales Report', 
'Direct vs Online Sales Comparison Report', 
'Review 2012 Sales Report and Approve 2016 Plans', 
'Deliver R&D Plans for 2016',
'Create 2016 R&D Plans', 
'2016 QA Strategy Report', 
'2016 Training Events', 
'Approve Hiring of John Jeffers', 
'Non-Compete Agreements', 
'Update NDA Agreement', 
'Update Employee Files with New NDA', 
'Sign Updated NDA',
'Submit Questions Regarding New NDA', 
'Submit Signed NDA', 
'Update Revenue Projections', 
'Review Revenue Projections', 
'Comment on Revenue Projections', 
'Provide New Health Insurance Docs',
'Review Changes to Health Insurance Coverage', 
'Scan Health Insurance Forms', 
'Sign Health Insurance Forms', 
'Follow up with West Coast Stores', 
'Follow up with East Coast Stores',
'Send Email to Customers about Recall', 
'Submit Refund Report for 2016 Recall', 
'Give Final Approval for Refunds', 
'Prepare Product Recall Report', 
'Review Product Recall Report by Engineering Team',
'Create Training Course for New TVs', 
'Review Training Course for any Ommissions', 
'Review Overtime Report', 
'Submit Overtime Request Forms', 
'Overtime Approval Guidelines', 
'Refund Request Template',
'Recall Rebate Form', 
'Create Report on Customer Feedback', 
'Review Customer Feedback Report', 
'Customer Feedback Report Analysis', 
'Prepare Shipping Cost Analysis Report', 
'Provide Feedback on Shippers',
'Select Preferred Shipper', 
'Complete Shipper Selection Form', 
'Upgrade Server Hardware', 
'Upgrade Personal Computers', 
'Approve Personal Computer Upgrade Plan', 
'Decide on Mobile Devices to Use in the Field',
'Upgrade Apps to Windows RT or stay with WinForms', 
'Estimate Time Required to Touch-Enable Apps', 
'Report on Tranistion to Touch-Based Apps', 
'Try New Touch-Enabled WinForms Apps',
'Rollout New Touch-Enabled WinForms Apps', 
'Site Up-Time Report', 
'Review Site Up-Time Report', 
'Review Online Sales Report', 
'Determine New Online Marketing Strategy', 
'New Online Marketing Strategy',
'Approve New Online Marketing Strategy', 
'Submit New Website Design', 
'Create Icons for Website', 
'Review PSDs for New Website', 
'Create New Shopping Cart', 
'Create New Product Pages', 
'Review New Product Pages',
'Approve Website Launch', 
'Launch New Website', 
'Update Customer Shipping Profiles', 
'Create New Shipping Return Labels', 
'Get Design for Shipping Return Labels', 
'PSD needed for Shipping Return Labels',
];