export const events = [{ id: 1, text: 'Prepare 2019 Financial' },
  { id: 2, text: 'Prepare 2019 Marketing Plan' },
  { id: 3, text: 'Update Personnel Files' },
  { id: 4, text: 'Review Health Insurance Options Under the Affordable Care Act' },
  { id: 5, text: 'New Brochures' },
  { id: 6, text: '2019 Brochure Designs' },
  { id: 7, text: 'Brochure Design Review' },
  { id: 8, text: 'Website Re-Design Plan' },
  { id: 9, text: 'Rollout of New Website and Marketing Brochures' },
  { id: 10, text: 'Create 2018 Sales Report' },
  { id: 11, text: 'Direct vs Online Sales Comparison Report' },
  { id: 12, text: 'Review 2018 Sales Report and Approve 2019 Plans' },
  { id: 13, text: 'Submit Signed NDA' },
  { id: 14, text: 'Update Revenue Projections' },
  { id: 15, text: 'Review Revenue Projections' },
  { id: 16, text: 'Comment on Revenue Projections' },
  { id: 17, text: 'Scan Health Insurance Forms' },
  { id: 18, text: 'Sign Health Insurance Forms' },
  { id: 19, text: 'Follow up with West Coast Stores' },
  { id: 20, text: 'Follow up with East Coast Stores' },
  { id: 21, text: 'Submit Refund Report for 2019 Recall' },
  { id: 22, text: 'Give Final Approval for Refunds' },
  { id: 23, text: 'Prepare Product Recall Report' },
  { id: 24, text: 'Review Product Recall Report by Engineering Team' },
  { id: 25, text: 'Review Training Course for any Ommissions' },
  { id: 26, text: 'Review Overtime Report' },
  { id: 27, text: 'Submit Overtime Request Forms' },
  { id: 28, text: 'Overtime Approval Guidelines' },
  { id: 29, text: 'Create Report on Customer Feedback' },
  { id: 30, text: 'Review Customer Feedback Report' }];

// export const events = [
// 'Prepare 2016 Financial', 
// 'Prepare 2016 Marketing Plan', 
// 'Update Personnel Files', 
// 'Review Health Insurance Options Under the Affordable Care Act', 
// 'New Brochures', 
// '2016 Brochure Designs', 
// 'Brochure Design Review', 
// 'Website Re-Design Plan', 
// 'Rollout of New Website and Marketing Brochures',
//  'Update Sales Strategy Documents', 
// 'Create 2012 Sales Report', 
// 'Direct vs Online Sales Comparison Report', 
// 'Review 2012 Sales Report and Approve 2016 Plans', 
// 'Deliver R&D Plans for 2016',
// 'Create 2016 R&D Plans', 
// '2016 QA Strategy Report', 
// '2016 Training Events', 
// 'Approve Hiring of John Jeffers', 
// 'Non-Compete Agreements', 
// 'Update NDA Agreement', 
// 'Update Employee Files with New NDA', 
// 'Sign Updated NDA',
// 'Submit Questions Regarding New NDA', 
// 'Submit Signed NDA', 
// 'Update Revenue Projections', 
// 'Review Revenue Projections', 
// 'Comment on Revenue Projections', 
// 'Provide New Health Insurance Docs',
// 'Review Changes to Health Insurance Coverage', 
// 'Scan Health Insurance Forms', 
// 'Sign Health Insurance Forms', 
// 'Follow up with West Coast Stores', 
// 'Follow up with East Coast Stores',
// 'Send Email to Customers about Recall', 
// 'Submit Refund Report for 2016 Recall', 
// 'Give Final Approval for Refunds', 
// 'Prepare Product Recall Report', 
// 'Review Product Recall Report by Engineering Team',
// 'Create Training Course for New TVs', 
// 'Review Training Course for any Ommissions', 
// 'Review Overtime Report', 
// 'Submit Overtime Request Forms', 
// 'Overtime Approval Guidelines', 
// 'Refund Request Template',
// 'Recall Rebate Form', 
// 'Create Report on Customer Feedback', 
// 'Review Customer Feedback Report', 
// 'Customer Feedback Report Analysis', 
// 'Prepare Shipping Cost Analysis Report', 
// 'Provide Feedback on Shippers',
// 'Select Preferred Shipper', 
// 'Complete Shipper Selection Form', 
// 'Upgrade Server Hardware', 
// 'Upgrade Personal Computers', 
// 'Approve Personal Computer Upgrade Plan', 
// 'Decide on Mobile Devices to Use in the Field',
// 'Upgrade Apps to Windows RT or stay with WinForms', 
// 'Estimate Time Required to Touch-Enable Apps', 
// 'Report on Tranistion to Touch-Based Apps', 
// 'Try New Touch-Enabled WinForms Apps',
// 'Rollout New Touch-Enabled WinForms Apps', 
// 'Site Up-Time Report', 
// 'Review Site Up-Time Report', 
// 'Review Online Sales Report', 
// 'Determine New Online Marketing Strategy', 
// 'New Online Marketing Strategy',
// 'Approve New Online Marketing Strategy', 
// 'Submit New Website Design', 
// 'Create Icons for Website', 
// 'Review PSDs for New Website', 
// 'Create New Shopping Cart', 
// 'Create New Product Pages', 
// 'Review New Product Pages',
// 'Approve Website Launch', 
// 'Launch New Website', 
// 'Update Customer Shipping Profiles', 
// 'Create New Shipping Return Labels', 
// 'Get Design for Shipping Return Labels', 
// 'PSD needed for Shipping Return Labels',
// ];